apiVersion: v1
kind: Service
metadata:
  name: godemo-svc
  namespace: background
spec:
  selector:
    app: godemo
  type: ClusterIP
  ports:
    - name: godemo-svc-http-port
      port: 8080
      targetPort: 8080

